### PR TITLE
Spawn various NPCs + NPC Fixes

### LINKED ISSUE #1067: TODO: Spawn Bridge Workers
Lakeshire, Bridge Workers
-------------------------------
images_4220

bridge3
bridge

We should spawn these Bridgeworkers, since they are low entries, they surely used old human models.

We could most likely see models push here, entry range matches display_id range
Capture d’écran_2023-03-26_18-31-32

 it's unsure but it will not be the first time that we see this model used for random workers
We could probably use it for all of them.

Here is new model push, it could be version 0.7/0.8 probably
Capture d’écran_2023-03-26_18-37-09

We should spawn theses workers
We should use placeholder model for them (one of  308, 309, 310)

### PR DESCRIPTION
**Pull request by Yushe**
Closes #1067 #1069 
Progress on #1070 #1016

We have screenshot proof of the location of some of the Programmer Isle NPCs so I thought I would spawn them in.

### CODE REVIEW

File: etc/databases/world/updates/updates.sql [hunk 1]
```diff
@@ -1474,5 +1474,49 @@ begin not atomic
 		insert into applied_updates values ('260320231');
 	end if;
 
+    -- 27/03/2023 1
+	if(select count(*) from applied_updates where id = '270320231') = 0 then
+		-- Placeholder display_id for Bridge Workers, correct levels & faction
+		update creature_template set display_id1 = 310, faction = 11 where entry in(648, 649, 650, 651, 652, 653);
+		update creature_template set level_min = 6, level_max = 6 where entry in(650, 651, 652, 653, 652, 653);
+		update creature_template set level_min = 10, level_max = 10 where entry = 649; -- Bridge Worker Dmitri only
+		update creature_template set level_min = 5, level_max = 5 where entry = 648; -- Bridge Worker Trent only
```
Comment (GrenderG) [inline etc/databases/world/updates/updates.sql:1483]: Where are the levels taken from? Also, I think we should spawn the remaining 2 workers even if they don't appear here:
image
probably they were spawned in front of the 3 that are next to the campfire, to the other side of it.

Comment (Yushe) [reply etc/databases/world/updates/updates.sql:1483]: Geo found the levels listed on a website and posted them within #1067 
I left the others unspawned because we don't know there exact position of them yet but I could spawn them on the other side of the campfire if you want me to.

Comment (GrenderG) [reply etc/databases/world/updates/updates.sql:1483]: Go for it. :)
