### PR TITLE
Hearthglen fixes

### LINKED ISSUE #983: TODO: Hearthglen (Western Plaguelands) needs a database do-over
**Describe what needs to be implemented or enhanced**
In vanilla, Hearthglen was an elite area full of Scarlet Crusade dudes. In 0.5.3 it was very likely completely devoid of life as Western Plaguelands were opened almost a *year* later in patch 0.10. Still, our data has all mobs spawned and correctly named, although everyone's running around shane cubed. 

There are also several game objects - including chests - spawned there which make no sense in the same context. They are shane cubes as well. The chests are either empty or contain unfinished loot.

Unfortunately we don't have any pictures from alpha (or even beta) showing Hearthglen, but I assume that's simply because there was nothing of interest there to find until shortly before retail release.

**Expected end result**
My personal idea would be to despawn all of this as it's borderline impossible to have been present in 0.5.3, but of course I can't prove anything. Looking for feedback on how to handle this.

### PR DESCRIPTION
**Pull request by mindphluxnet**
Closes #983 

Also despawns the unused Tool Bucket gameobjects.

### CODE REVIEW

**Comment by mindphluxnet** [comment]
He means one is male, the other female.

File: etc/databases/world/updates/updates.sql [hunk 1]
```diff
@@ -949,5 +949,36 @@ begin not atomic
...
+        update creature_template set display_id1 = 1611 where entry = 1844; -- Foreman Marcrid
+        update creature_template set display_id1 = 1025 where entry = 1845; -- High Protector Tarsen
+        update creature_template set display_id1 = 1025 where entry = 1846; -- High Protector Lorik
+        update creature_template set display_id1 = 1617, display_id2 = 1615, display_id3 = 0, display_id4 = 0 where entry = 1883; -- Scarlet Worker
+        update creature_template set display_id1 = 1025 where entry = 1842; -- Highlord Taelan Fordring
+        update creature_template set display_id1 = 2520, display_id2 = 2521, display_id3 = 0, display_id4 = 0 where entry = 1884; -- Scarlet Lumberjack
+        update creature_template set display_id1 = 2465, display_id2 = 2476, display_id3 = 0, display_id4 = 0 where entry = 1885; -- Scarlet Smith
+
+        -- Remove Tool Bucket spawns from Hearthglen as the associated quest doesn't exist
+        delete from spawns_gameobjects where spawn_entry = 177726;
```
Comment (GrenderG) [inline etc/databases/world/updates/updates.sql:978]: Please set as ignored instead of deleting. :pray: (only use delete if it's something we manually spawned like the duplicate NPC spawns from the recent PR).

Comment (GrenderG) [reply etc/databases/world/updates/updates.sql:978]: The idea to use ignored instead of deleting came because:

1. This way if we ever find (for some reason) that something was indeed spawned, we don't need to add it from scratch.
2. Our database can be used in the future (by ourselves or by another person) to build a database for newer beta versions or whatever. Unlikely to happen, but you never know!

**Comment by geo-tp** [comment]
As @mindphluxnet  said, for male and female, so both should be used.
