### PR TITLE
Fixes for several issues

### LINKED ISSUE #552: [Item/Quest] Incorrect item name and quest objective.
**Describe the bug**
The quest A Recipe for Death (ID 447) asks, among other things, for 6 stacks of Skittering Blood (ID 3254). The name of the item is incorrect, since in 0.5.3 it was called Spider Marrow. The change to Skittering blood was done in the next patch, 0.5.4.
Spider Marrow doesn't exist in the database, so most likely its ID was used for the Skittering blood later on.

**Expected behavior**
Both the quest and the item should display the correct item name of Spider Marrow

**Source**
Official Blizzard Patch-Notes from patch 0.5.4
The exact amount of how many hearts and marrows are needed is still investigated, since the current quantity of 6 is obviously wrong but solid proof is needed to change it.
AF and RfD

### LINKED ISSUE #577: [icon] Grayson's Torch's missing icon.
**Describe the bug**
Grayson's torch (ID 1172) should have the inv-spear-03 (ID 135126) icon. If anyone has doubts about torches having spear icons (like I did), both the Dim Torch (ID 6182) and Monster - Torch, Offhand (ID 2081) have the exact icon in game, so it seems that it was a common thing back then.

**Sources**
NoBans

### LINKED ISSUE #821: TODO:  Move Rellian Greespyre
**Describe what needs to be implemented or enhanced**
wow_art_darnassus

**Expected end result**
3517 Rellian Greenspyre should be moved to darnassus entrance, display_id should be 2572 
https://db.thealphaproject.eu/index.php?action=show_creature&id=3517&filter=greenspy&sort_order=name&pos=1&max=1

### LINKED ISSUE #823: TODO: Coldridge Valley Rework
- [ ] Change [Father Gavin](https://db.thealphaproject.eu/index.php?action=show_creature&id=1253&filter=gavin&sort_order=name&pos=2&max=3)'s level and faction

His LvL is supposed to be 15.
He should be friendly with the Alliance. Currently he is neutral and attackable by the alliance.

**Source** from 0.5.5 (shot between 22-26/03/2004)

- [ ] Change [Senir Whitebeard](https://db.thealphaproject.eu/index.php?action=show_creature&id=1252&filter=Senir&sort_order=name&pos=1&max=1)'s level to 9

**Source** from 0.5.5 (shot between 22-26/03/2004)

- [ ] Unequip [Ozzie Togglevolt](https://db.thealphaproject.eu/index.php?action=show_creature&id=1268&filter=ozzie&sort_order=name&pos=1&max=1)'s and [Razzle Spysprocket](https://db.thealphaproject.eu/index.php?action=show_creature&id=1269&filter=razzle&sort_order=name&pos=2&max=2)'s tools.

**Source** from 0.5.5 (shot between 22-26/03/2004)

- [ ] Change [Pilot Stonegear](https://db.thealphaproject.eu/index.php?action=show_creature&id=1377&filter=stonegear&sort_order=name&pos=1&max=1)'s DisplayID to 115, 312, 803, 824, 826 ,832, 1764, 2584 or 3232 (they're all the same)

**Source** from 0.5.5 (shot between 22-26/03/2004)

### LINKED ISSUE #899: TODO: Remove "Bundle of Wood" placeholder boxes from Elwynn Forest
**Describe what needs to be implemented or enhanced**
At the logging camp in Elwynn Forest you can find a grand total of 25 placeholder boxes representing "[Bundle of Wood](https://db.thealphaproject.eu/index.php?action=show_go&id=176793&filter=Bundle+of+Wood&sort_order=name&pos=1&max=1)" for a quest that wasn't yet implemented in 0.5.3. Example:

image

spawn_entry is 176793

**Expected end result**
A litter-free Elwynn Forest logging camp

**Guidance**
```
DELETE FROM `spawns_gameobjects` WHERE `spawn_entry` = 176793;
```

Done.

### LINKED ISSUE #901: TODO: Remove placeholder cubes from Valley of Trials, Durotar
**Describe what needs to be implemented or enhanced**

Same issue as #899 - the wood piles here are from a quest that has not yet been implemented. As they are not needed they should be removed.

image

**Expected end result**
Another subzone litter free!

**Guidance**
I'll add a PR myself.

### LINKED ISSUE #904: Sentinel Hill, Westfall: NPC stuck in the ground
**Describe the bug**
At Sentinel Hill, Westfall, a lumberjack NPC is stuck in the ground due to a wrong Z coordinate.

**Steps to reproduce**
1. Visit Sentinel Hill, Westfall
2. Check on the lumberjack in front of the sawmill

**Expected behavior**
He's not supposed to be stuck in the ground.

**Screenshots**
image

**Suggestion** 

Set his Z coordinate to 34.408

### LINKED ISSUE #905: Enemy creatures aggro when player is on a taxi
**Describe the bug**
While the player is on a taxi route, enemies the player flies near to aggro and occasionally even manage to get a hit in.

**Steps to reproduce**
1. With a level appropiate character, fly from Stormwind to Sentinel Hill, Westfall
2. Listen to enemies play their aggro sound
3. Get hit by a Dust Devil shortly before landing in Westfall

**Expected behavior**
Players on a taxi service should be ignored by enemies.

**Screenshots**
https://youtu.be/MdNLAcl9H0I

**Sources**
Of course I can't be sure this isn't working as intended in 0.5.3 but it sure seems like a bug.

### PR DESCRIPTION
**Pull request by mindphluxnet**
Closes #577
Closes #899 
Closes #901 
Closes #904 
Closes #905 
Closes #823 
Closes #552 
Closes #821 

Affects #328
Affects #834

### CODE REVIEW

**Comment by mindphluxnet** [comment]
Also partially fixes #328

File: etc/databases/world/updates/updates.sql [hunk 1]
```diff
@@ -16609,5 +16609,26 @@ begin not atomic
 
         INSERT INTO applied_updates VALUES ('110220232');
     end if;
+
+    -- 12/02/2023 1
+    if (select count(*) from applied_updates where id = '120220231') = 0 then
+        -- remove placeholder objects from Elwynn Forest
+        DELETE FROM `spawns_gameobjects` WHERE `spawn_entry` = 176793;
+        -- remove placeholder objects from Valley of Trials, Durotar
+        DELETE FROM `spawns_gameobjects` WHERE `spawn_entry` = 175784;
```
Comment (GrenderG) [inline etc/databases/world/updates/updates.sql:16618]: Please instead of removing spawns, set `ignored` to `1` in the database.

File: game/world/managers/objects/units/creature/CreatureManager.py [hunk 2]
```diff
@@ -606,7 +606,7 @@ def _check_time_to_live(self, elapsed):
         return True
 
     # override
-    def attack(self, victim: UnitManager):
+    def attack(self, victim: UnitManager):
```
Comment (GrenderG) [inline game/world/managers/objects/units/creature/CreatureManager.py:609]: Extra tab? :P

File: etc/databases/world/updates/updates.sql [hunk 3]
```diff
@@ -16609,5 +16609,54 @@ begin not atomic
...
+
+        INSERT INTO applied_updates VALUES ('130220231');
+    end if;
+
+    -- 14/02/2023 1
+    if (select count(*) from applied_updates where id = '140220231') = 0 then
+        -- change Father Gavin's level and faction        
+        UPDATE `creature_template` SET `level_min` = 15, `level_max` = 15, `faction` = 35 WHERE `entry` = 1253;
+        -- change Senir Whitebeard's level to 9
+        UPDATE `creature_template` SET `level_min` = 9, `level_max` = 9 WHERE `entry` = 1252;
```
Comment (GrenderG) [inline etc/databases/world/updates/updates.sql:16638]: See https://github.com/The-Alpha-Project/alpha-core/issues/823#issuecomment-1433614304

File: etc/databases/world/updates/updates.sql [hunk 4]
```diff
@@ -16609,5 +16609,54 @@ begin not atomic
...
+        -- Uneqip Ozzie Togglevolt's tool
+        UPDATE `creature_template` SET `equipment_id` = 0 WHERE `entry` = 1268;
+        -- Unequip Razzle Spysprocket's tool
+        UPDATE `creature_template` SET `equipment_id` = 0 WHERE `entry` = 1269;
+        -- Set Pilot Stonegear's display_id to a proper value
+        UPDATE `creature_template` SET `display_id1` = 115 WHERE `entry` = 1377;
```
Comment (GrenderG) [inline etc/databases/world/updates/updates.sql:16644]: Considering the display_id range of other NPCs around him, seems like he should have `3232` display_id.

File: etc/databases/world/updates/updates.sql [hunk 5]
```diff
@@ -16609,5 +16609,54 @@ begin not atomic
...
+    end if;
+
+    -- 14/02/2023 2
+    if (select count(*) from applied_updates where id = '140220232') = 0 then
+        -- Change details of quest 447
+        UPDATE `quest_template` SET `Objectives` = 'Collect 6 Grizzled Bear Hearts and 6 samples of Spider Marrow and deliver them to Master Apothecary Faranell in the Undercity.', `Details` = "Arthas's numbers are overwhelming. But with a New Plague we could eradicate both the Scourge Army and the Human infestation once and for all.$b$bMy studies have proven that spider marrow combined with a toxin derived from a grizzled bear heart results in a deadly elixir. Collect samples from the spiders in the Skittering Dark to the northwest and from the bears wandering throughout Silverpine Forest. Deliver the reagents to Master Apothecary Faranell of the Royal Apothecary Society in the Undercity." WHERE `entry` = 447;
+        -- rename Skittering Blood to Spider Marrow
+        UPDATE `item_template` SET `name` = 'Spider Marrow' WHERE `entry` = 3254;
+        -- change Frank Ward's faction to friendly
+        UPDATE `creature_template` SET `faction` = 35 WHERE `entry` = 2940;
```
[the remark this answers is not in the document]
Comment (mindphluxnet) [reply etc/databases/world/updates/updates.sql:16656]: Yep, done.

File: etc/databases/world/updates/updates.sql (hunk 4 above)
Comment (mindphluxnet) [reply etc/databases/world/updates/updates.sql:16644]: While he does look completely different in Classic WoW your suggestion also makes sense given that 3232 is unused. I changed it.

**Comment by GrenderG** [comment]
Thanks! Please @mindphluxnet leave a comment on #328 and #834 mentioning what has been fixed with this PR.
